#!/bin/bash
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
IFS=$'\t' read -r PRODUCT_NAME PRODUCT_VERSION PRODUCT_REPO MAC_ARCHIVE LINUX_ARCHIVE EXECUTABLE < "$REPO/manifests/product.tsv"
APP="$REPO/dist/$PRODUCT_NAME.app"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources/scripts" "$APP/Contents/Resources/manifests" "$APP/Contents/Resources/resources"
xcrun swiftc -parse-as-library -O -target arm64-apple-macos15.0 \
  "$REPO"/Sources/*.swift -o "$APP/Contents/MacOS/$EXECUTABLE"
cp "$REPO/scripts/downloads.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/security.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/backend.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/platform-macos.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/online.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/settings.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/native-mods.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/steam-webhelper.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/sage.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/compatibility.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/classic.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO"/manifests/*.txt "$APP/Contents/Resources/manifests/"
cp "$REPO/scripts/steam-status.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/manifests/steam-webhelper.sha256" "$APP/Contents/Resources/manifests/"
cp -R "$REPO/resources/steam-webhelper" "$APP/Contents/Resources/resources/"
cp "$REPO"/manifests/*.tsv "$APP/Contents/Resources/manifests/"
cp "$REPO/resources/max-options.ini" "$APP/Contents/Resources/resources/"
cp "$REPO/resources/balanced-options.ini" "$APP/Contents/Resources/resources/"
find "$APP/Contents/Resources/resources" -maxdepth 1 -type f -name '*.json' -delete
cp "$REPO"/resources/*.json "$APP/Contents/Resources/resources/"
cp "$REPO/resources/Info.plist" "$APP/Contents/"
cp "$REPO/resources/Launcher.icns" "$APP/Contents/Resources/"
cp "$REPO/LICENSE" "$APP/Contents/Resources/"
cp "$REPO/THIRD-PARTY-NOTICES.md" "$APP/Contents/Resources/"
codesign --force --deep --sign - "$APP"
ditto -c -k --sequesterRsrc --keepParent "$APP" "$REPO/dist/$MAC_ARCHIVE"
printf 'Built %s\n' "$APP"
