#!/bin/bash
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
APP="$REPO/dist/GeneralsX Launcher.app"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources/scripts" "$APP/Contents/Resources/manifests" "$APP/Contents/Resources/resources"
xcrun swiftc -parse-as-library -O -target arm64-apple-macos15.0 \
  "$REPO"/Sources/*.swift -o "$APP/Contents/MacOS/GeneralsXLauncher"
cp "$REPO/scripts/backend.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/platform-macos.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO/scripts/classic.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO"/manifests/*.txt "$APP/Contents/Resources/manifests/"
cp "$REPO/scripts/steam-status.sh" "$APP/Contents/Resources/scripts/"
cp "$REPO"/manifests/*.tsv "$APP/Contents/Resources/manifests/"
cp "$REPO/resources/max-options.ini" "$APP/Contents/Resources/resources/"
cp "$REPO/resources/balanced-options.ini" "$APP/Contents/Resources/resources/"
cp "$REPO"/resources/*.json "$APP/Contents/Resources/resources/"
cp "$REPO/resources/Info.plist" "$APP/Contents/"
cp "$REPO/resources/Launcher.icns" "$APP/Contents/Resources/"
cp "$REPO/LICENSE" "$APP/Contents/Resources/"
codesign --force --deep --sign - "$APP"
ditto -c -k --sequesterRsrc --keepParent "$APP" "$REPO/dist/GeneralsX-Launcher-macOS-arm64.zip"
printf 'Built %s\n' "$APP"
