FROM python:3.12-slim-bookworm
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl file zip unzip xz-utils procps wine wine64 libwine libvulkan1 binutils lib32gcc-s1 lib32stdc++6 libglib2.0-0 libegl1 libgl1 \
    libdbus-1-3 libxkbcommon0 libfontconfig1 libxcb-cursor0 libx11-xcb1 \
    libxkbcommon-x11-0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0 libxcb-xkb1 \
    libgtk-3-0 xvfb xauth \
    && rm -rf /var/lib/apt/lists/*
COPY linux/requirements.lock /tmp/requirements.lock
RUN pip install --no-cache-dir --require-hashes -r /tmp/requirements.lock
ENV QT_QPA_PLATFORM=offscreen
WORKDIR /project
